#! /bin/bash

mkdir cfg_backup
echo Backing up core-site.xml...
cp /usr/local/hadoop-3.3.6/etc/hadoop/core-site.xml ~/cfg_backup/core-site.xml
echo Modifying core-site.xml...
echo ~~~~~~~~~~~~~~~~~~~~~~~~~~

echo Backing up hdfs-site.xml...
cp /usr/local/hadoop-3.3.6/etc/hadoop/hdfs-site.xml ~/backcfg_backupup/hdfs-site.xml
echo Modifying hdfs-site.xml...
echo ~~~~~~~~~~~~~~~~~~~~~~~~~~


echo Backing up mapred-site.xml...
cp /usr/local/hadoop-3.3.6/etc/hadoop/yarn-site.xml ~/cfg_backup/yarn-site.xml
echo Modifying mapred-site.xml...
echo ~~~~~~~~~~~~~~~~~~~~~~~~~~

echo Backing up yarn-site.xml...
cp /usr/local/hadoop-3.3.6/etc/hadoop/yarn-site.xml ~/cfg_backup/yarn-site.xml
echo Modifying yarn-site.xml...
echo ~~~~~~~~~~~~~~~~~~~~~~~~~~

echo Stopping Hadoop DFS...
stop-dfs.sh
echo Stopping YARN...
stop-yarn.sh
echo Starting Hadoop DFS...
start-dfs.sh
echo Starting YARN...
start-yarn.sh
echo Configuration changes applied and services restarted.